name: checkov

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build backend docker
      run: ../../backend/Dockerfile .
    - name: Run Checkov vulnerability scanner for the backend
      run: checkov -f ../../backend/Dockerfile
    - name: Build frontend docker
      run: ../../frontend/Dockerfile .
    - name: Run Checkov vulnerability scanner for the frontend
      run: checkov -f ../../frontend/Dockerfile
