name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
    - uses: aquasecurity/trivy-action@0.68.2
    - run: trivy fs --format cyclonedx --output result.json ./task-manager/ --scanners vuln
